# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ebb54f39054c82887b25420a25ab827839d7ed35bfa4ed229fa13d38bca66ac7a15b9d0b108f6346c290b57656f984dbf1d028292874f0606e61f1cfd60c5ec

test:
  secret_key_base: 0cf539234ed41a56e37a3e4257de18da8c6b6d76182a71a5f112e889bc34e9ee4af3f5bc83b805f2ce61ef69e26dd919f57ff7a06270190316267d3033682f88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
